### ISSUE TITLE
Build fails on missing autogenerated_computed.h

### ISSUE THREAD

**Issue by Phantop** [CobaltBSD/neosurf#29]
Happens on Arch Linux:

```sh
make: Entering directory '/home/glados/Downloads/neosurf/build'
[  1%] Built target parserutils
[  2%] Built target nsutils
[  2%] Building C object contrib/libcss/CMakeFiles/css.dir/src/select/properties/helpers.c.o
In file included from /home/glados/Downloads/neosurf/contrib/libcss/src/select/propget.h:12,
                 from /home/glados/Downloads/neosurf/contrib/libcss/src/select/properties/helpers.c:13:
/home/glados/Downloads/neosurf/contrib/libcss/src/select/computed.h:15:10: fatal error: autogenerated_computed.h: No such file or directory
   15 | #include "autogenerated_computed.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [contrib/libcss/CMakeFiles/css.dir/build.make:2344: contrib/libcss/CMakeFiles/css.dir/src/select/properties/helpers.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:309: contrib/libcss/CMakeFiles/css.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
make: Leaving directory '/home/glados/Downloads/neosurf/build'
```
The file *does* exist in the build folder, which tells me that includes aren't being done correctly in some capacity.

**Comment by r1bilski** [comment]
It seems that the following change in 0e6a08e is responsible for that error. 
Reverting that change fixes the build.

```
index e25b540..c763bc6 100644
--- a/contrib/libcss/src/select/select_generator.py
+++ b/contrib/libcss/src/select/select_generator.py
@@ -820,7 +820,7 @@ class CSSGroup:
             raise ValueError()
 
 css_groups = [ CSSGroup(g) for g in groups ]
-dir_path = sys.argv[1]
+dir_path = sys.argv[1] + "/contrib/libcss"
 
 for k, v in assets.items():
     # Key is filename string (e.g. "computed.h") without autogenerated_ prefix
```

**Comment by Phantop** [comment]
It does build now, however running `neosurf-gtk` fails as follows;
```sh
Options failed to initialise (BadParameter)
NeoSurf gtk failed to initialise (BadParameter)
```

**Comment by CobaltBSD** [comment]
This should be fixed in the latest commit.

**Comment by r1bilski** [comment]
I can confirm it works.

**Comment by Phantop** [comment]
The build issues are good but the error I mentioned above still occurs on launch.

**Comment by CobaltBSD** [comment]
> The build issues are good but the error I mentioned above still occurs on launch.

I will look more closely into what might be causing this when I get a chance, but I haven't been able to reproduce this. Try deleting /usr/share/neosurf-gtk and /usr/share/neosurf (or wherever said files were installed), and then reinstall.

**Comment by Phantop** [comment]
The issue happens consistently for me when building using [this](https://aur.archlinux.org/packages/neosurf-git) PKGBUILD.

**Comment by CobaltBSD** [comment]
> The issue happens consistently for me when building using [this](https://aur.archlinux.org/packages/neosurf-git) PKGBUILD.

It would be good if the maintainer of that AUR entry @nicolarevelant update it when he has the chance. The PKGBUILD script itself works with the latest commit of Neosurf.

**Comment by nicolarevelant** [comment]
What's the problem with my PKGBUILD?
